name: Request a feature
description: Share ideas for new features
title: "[Feature Request]: "
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        <!-- Please describe the feature you would like to see implemented. -->
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Please provide any additional context or information that may be helpful in understanding your request
      placeholder: "e.g. use case, related features, etc."
